# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer2.papernet.com:
  orderer3.papernet.com:
  orderer4.papernet.com:
  orderer5.papernet.com:

networks:
  papernet:

services:

  orderer2.papernet.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=8050
    container_name: orderer2.papernet.com
    networks:
    - papernet
    volumes:
        - ./channel-artifacts/genesisRaft.block:/var/hyperledger/orderer/orderer.genesisRaft.block
        - ./crypto-config/ordererOrganizations/papernet.com/orderers/orderer2.papernet.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/papernet.com/orderers/orderer2.papernet.com/tls/:/var/hyperledger/orderer/tls
        - orderer2.papernet.com:/var/hyperledger/production/orderer
    ports:
    - 8050:8050


  orderer3.papernet.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=9050
    container_name: orderer3.papernet.com
    networks:
    - papernet
    volumes:
        - ./channel-artifacts/genesisRaft.block:/var/hyperledger/orderer/orderer.genesisRaft.block
        - ./crypto-config/ordererOrganizations/papernet.com/orderers/orderer3.papernet.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/papernet.com/orderers/orderer3.papernet.com/tls/:/var/hyperledger/orderer/tls
        - orderer3.papernet.com:/var/hyperledger/production/orderer
    ports:
    - 9050:9050


  orderer4.papernet.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=10050
    container_name: orderer4.papernet.com
    networks:
    - papernet
    volumes:
        - ./channel-artifacts/genesisRaft.block:/var/hyperledger/orderer/orderer.genesisRaft.block
        - ./crypto-config/ordererOrganizations/papernet.com/orderers/orderer4.papernet.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/papernet.com/orderers/orderer4.papernet.com/tls/:/var/hyperledger/orderer/tls
        - orderer4.papernet.com:/var/hyperledger/production/orderer
    ports:
    - 10050:10050


  orderer5.papernet.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=11050
    container_name: orderer5.papernet.com
    networks:
    - papernet
    volumes:
        - ./channel-artifacts/genesisRaft.block:/var/hyperledger/orderer/orderer.genesisRaft.block
        - ./crypto-config/ordererOrganizations/papernet.com/orderers/orderer5.papernet.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/papernet.com/orderers/orderer5.papernet.com/tls/:/var/hyperledger/orderer/tls
        - orderer5.papernet.com:/var/hyperledger/production/orderer
    ports:
    - 11050:11050
